
const KEY='video-shelf-v1',seed=[];
const categories={unclassified:'미분류',animation:'애니메이션',movie:'영화',other:'기타'},presets={animation:['에반게리온','블루록','소년탐정 김전일'],movie:['검은 사제들']};let selectedCategory='all',selectedWork='';
function normalize(v){return {...v,category:Object.hasOwn(categories,v.category)?v.category:'unclassified',work:v.work||''}}
const $=id=>document.getElementById(id);let videos=seed.map(v=>({...v})),filter='all',editing=null,timer;
function valid(v){return v&&typeof v.id==='string'&&/^[A-Za-z0-9_-]{11}$/.test(v.id)&&typeof v.title==='string'&&v.title.length<=180&&['unknown','ok','blocked'].includes(v.status)&&typeof v.note==='string'&&v.note.length<=2000&&(v.category===undefined||typeof v.category==='string'&&/^[a-z][a-z0-9_-]{0,79}$/.test(v.category)&&!['__proto__','constructor','prototype','all'].includes(v.category))&&(v.thumbnailFileId===undefined||typeof v.thumbnailFileId==='string'&&/^[A-Za-z0-9_-]{1,200}$/.test(v.thumbnailFileId))&&(v.work===undefined||typeof v.work==='string'&&v.work.length<=100)}
function catalogValid(c,p){return c&&typeof c==='object'&&!Array.isArray(c)&&c.unclassified==='미분류'&&Object.keys(c).length<=100&&Object.entries(c).every(([k,v])=>/^[a-z][a-z0-9_-]{0,79}$/.test(k)&&!['__proto__','constructor','prototype','all'].includes(k)&&typeof v==='string'&&v.trim()&&v.length<=60)&&p&&typeof p==='object'&&!Array.isArray(p)&&Object.entries(p).every(([k,ws])=>Object.hasOwn(c,k)&&Array.isArray(ws)&&ws.length<=1000&&ws.every(w=>typeof w==='string'&&w.trim()&&w.length<=100))}
function applyCatalog(c,p){for(const k of Object.keys(categories))delete categories[k];Object.assign(categories,c);for(const k of Object.keys(presets))delete presets[k];Object.assign(presets,p)}
try{const data=JSON.parse(localStorage.getItem(KEY));if(Array.isArray(data)&&data.every(valid))videos=data;else if(data?.version===2&&catalogValid(data.categories,data.presets)&&Array.isArray(data.videos)&&data.videos.every(valid)){applyCatalog(data.categories,data.presets);videos=data.videos}}catch{}
videos=videos.map(normalize);
function toast(t){$('toast').textContent=t;$('toast').hidden=false;clearTimeout(timer);timer=setTimeout(()=>$('toast').hidden=true,3500)}
function save(){try{localStorage.setItem(KEY,JSON.stringify(backup()));if(window.WatchpartyDrive)window.WatchpartyDrive.changed();return true}catch{toast('저장이 제한되어 있습니다. 목록을 내보내서 보관해주세요.');return false}}
function backup(){return {version:2,categories,presets,videos}}
function node(tag,cls,txt){const el=document.createElement(tag);if(cls)el.className=cls;if(txt!==undefined)el.textContent=txt;return el}
function worksFor(c){return [...new Set([...(presets[c]||[]),...videos.filter(v=>c==='all'||v.category===c).map(v=>v.work).filter(Boolean)])]}
function renderCollections(){
 $('categories').replaceChildren();[['all','전체'],...Object.entries(categories)].forEach(([key,label])=>{const b=node('button','category-tab'+(selectedCategory===key?' active':''));b.append(node('span','',label),node('small','',String(videos.filter(v=>key==='all'||v.category===key).length)));b.setAttribute('aria-pressed',String(selectedCategory===key));b.onclick=()=>{selectedCategory=key;selectedWork='';render()};$('categories').append(b)});
 $('works').replaceChildren();if(selectedCategory!=='all'){[['','전체 작품'],...worksFor(selectedCategory).map(w=>[w,w])].forEach(([key,label])=>{const b=node('button','work-chip'+(selectedWork===key?' active':''),label);b.setAttribute('aria-pressed',String(selectedWork===key));b.onclick=()=>{selectedWork=key;render()};$('works').append(b)})}
 $('categoryHint').textContent=selectedCategory==='unclassified'?'영상 카드의 편집에서 카테고리와 작품명을 지정하세요.':selectedWork?selectedWork+'에 속한 영상을 모아봅니다.':'카테고리를 누르면 작품별로 모아볼 수 있습니다.';
}
function suggestions(){const c=$('category').value;$('workSuggestions').replaceChildren(...worksFor(c).map(w=>{const o=node('option');o.value=w;return o}))}
function render(){if(window.WatchpartyDrive)window.WatchpartyDrive.releaseThumbnails();renderCollections();const q=$('search').value.trim().toLowerCase(),list=videos.filter(v=>(filter==='all'||v.status===filter)&&(selectedCategory==='all'||v.category===selectedCategory)&&(!selectedWork||v.work===selectedWork)&&[v.title,v.note,v.id,v.work,categories[v.category]].join(' ').toLowerCase().includes(q));$('count').textContent=`전체 ${videos.length}개 · 표시 ${list.length}개`;$('grid').replaceChildren();if(!list.length){$('grid').append(node('div','empty','조건에 맞는 영상이 없습니다.'));return}list.forEach(v=>{const card=node('article','card'),link=node('a','visual');link.href='https://youtu.be/'+v.id;link.target='_blank';link.rel='noopener noreferrer';link.setAttribute('aria-label',v.title+' 유튜브에서 열기');const fallback=node('div','fallback');fallback.append(node('b','','▸'),node('span','','저장한 영상'),node('small','',v.id));const img=node('img');img.src='https://i.ytimg.com/vi/'+v.id+'/hqdefault.jpg';img.alt=v.title+' 썸네일';img.loading='lazy';img.referrerPolicy='no-referrer';img.onerror=()=>{img.hidden=true};img.onload=()=>{img.hidden=img.naturalWidth<=120&&!img.src.startsWith('blob:')};if(window.WatchpartyDrive)window.WatchpartyDrive.showThumbnail(v,img);link.append(fallback,img,node('span','play','▶'));const body=node('div','body'),meta=node('div','meta');meta.append(node('span','badge '+v.status,{unknown:'미확인',ok:'정상',blocked:'차단'}[v.status]),node('span','number',String(videos.indexOf(v)+1).padStart(2,'0')));const actions=node('div','actions'),open=node('a','open','유튜브에서 열기 ↗');open.href=link.href;open.target='_blank';open.rel=link.rel;const edit=node('button','edit','편집');edit.onclick=()=>show(v.id);actions.append(open,edit);body.append(meta,node('p','collection-label',categories[v.category]+(v.work?' · '+v.work:'')),node('h2','',v.title),node('p','note',v.note||'메모 없음'),actions);card.append(link,body);$('grid').append(card)})}
function parseURL(raw){try{const u=new URL(raw.trim());if(!['https:','http:'].includes(u.protocol))return null;let id;if(u.hostname==='youtu.be')id=u.pathname.split('/')[1];else if(['youtube.com','www.youtube.com','m.youtube.com','music.youtube.com'].includes(u.hostname))id=u.searchParams.get('v')||(/\/(shorts|embed|live)\//.test(u.pathname)?u.pathname.split('/')[2]:null);return /^[A-Za-z0-9_-]{11}$/.test(id||'')?id:null}catch{return null}}
function show(id=null){editing=id;const v=videos.find(v=>v.id===id);$('form').reset();categoryOptions($('category'));$('error').textContent='';$('dialogTitle').textContent=v?'영상 편집':'영상 추가';$('delete').hidden=!v;if(v){$('url').value='https://youtu.be/'+v.id;$('title').value=v.title;$('status').value=v.status;$('note').value=v.note;$('category').value=v.category;$('work').value=v.work}else{$('category').value=selectedCategory==='all'?'unclassified':selectedCategory;$('work').value=selectedWork}suggestions();$('dialog').showModal()}
$('category').onchange=()=>{ $('work').value='';suggestions()};$('add').onclick=()=>show();$('cancel').onclick=()=>$('dialog').close();$('search').oninput=render;document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});render()});
$('form').onsubmit=async e=>{e.preventDefault();const id=parseURL($('url').value);if(!id){$('error').textContent='올바른 유튜브 영상 주소를 입력해주세요.';return}if(videos.some(v=>v.id===id&&v.id!==editing)){$('error').textContent='이미 목록에 있는 영상입니다.';return}const v={id,title:$('title').value.trim()||'저장한 영상 · '+id,status:$('status').value,note:$('note').value.trim(),category:$('category').value,work:$('work').value.trim()};const previous=videos.find(x=>x.id===editing);if(previous?.thumbnailFileId&&id===editing)v.thumbnailFileId=previous.thumbnailFileId;const file=$('thumbnail').files?.[0];if(file){try{await window.WatchpartyDrive.storeThumbnail(id,file);delete v.thumbnailFileId}catch(err){$('error').textContent=err.message;return}}if(editing)videos=videos.map(x=>x.id===editing?v:x);else videos.unshift(v);const saved=save();
render();$('dialog').close();if(saved)toast('이 브라우저에 저장했습니다.')};
$('delete').onclick=()=>{if(!confirm('이 영상의 링크와 메모를 목록에서 삭제할까요?'))return;videos=videos.filter(v=>v.id!==editing);save();render();$('dialog').close()};
$('export').onclick=()=>{const blob=new Blob([JSON.stringify(backup(),null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=node('a');a.href=u;a.download='내-영상-목록.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)};$('import').onclick=()=>$('file').click();$('file').onchange=async()=>{const file=$('file').files[0];if(!file)return;try{if(file.size>3000000)throw Error();const raw=JSON.parse(await file.text()),data=Array.isArray(raw)?raw:raw.videos;if(!Array.isArray(data)||!data.every(valid))throw Error();let mapping={};if(!Array.isArray(raw)){if(raw.version!==2||!catalogValid(raw.categories,raw.presets))throw Error();for(const [key,name] of Object.entries(raw.categories)){let mapped=Object.keys(categories).find(k=>categories[k]===name);if(!mapped){mapped=!Object.hasOwn(categories,key)?key:newCategoryId();categories[mapped]=name}mapping[key]=mapped;presets[mapped]=[...new Set([...(presets[mapped]||[]),...(raw.presets[key]||[])])]}}let added=0;data.forEach(v=>{if(!videos.some(x=>x.id===v.id)){videos.push({id:v.id,title:v.title,status:v.status,note:v.note,category:mapping[v.category]||(Object.hasOwn(categories,v.category)?v.category:'unclassified'),work:v.work||'',...(v.thumbnailFileId?{thumbnailFileId:v.thumbnailFileId}:{})});added++}});const saved=save();render();if(saved)toast(`${added}개를 가져왔습니다. 중복 영상은 건너뛰었습니다.`)}catch{toast('올바른 영상 목록 JSON 파일을 선택해주세요.')}finally{$('file').value=''}};
function categoryOptions(select){const previous=select.value;select.replaceChildren(...Object.entries(categories).map(([k,name])=>{const o=node('option','',name);o.value=k;return o}));select.value=Object.hasOwn(categories,previous)?previous:'unclassified'}
function newCategoryId(){let id;do{id='custom_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8)}while(Object.hasOwn(categories,id));return id}
function manageError(t){$('manageError').textContent=t}
function persistManagement(){save();render();renderManager();toast('카테고리 변경을 적용했습니다.')}
function renameCategory(key,name){name=name.trim();if(!name||name.length>60)throw Error('카테고리 이름을 1~60자로 입력하세요.');if(key==='unclassified')throw Error('미분류는 이름을 변경할 수 없습니다.');if(Object.entries(categories).some(([k,n])=>k!==key&&n===name))throw Error('이미 있는 카테고리 이름입니다.');categories[key]=name}
function deleteCategory(key){if(key==='unclassified')throw Error('미분류는 삭제할 수 없습니다.');videos=videos.map(v=>v.category===key?{...v,category:'unclassified'}:v);delete categories[key];delete presets[key];if(selectedCategory===key){selectedCategory='all';selectedWork=''}}
function renameWork(key,oldName,newName){newName=newName.trim();if(!newName||newName.length>100)throw Error('작품명을 1~100자로 입력하세요.');if(newName!==oldName&&worksFor(key).includes(newName))throw Error('이미 있는 작품명입니다.');presets[key]=[...new Set(worksFor(key).map(w=>w===oldName?newName:w))];videos=videos.map(v=>v.category===key&&v.work===oldName?{...v,work:newName}:v);if(selectedCategory===key&&selectedWork===oldName)selectedWork=newName}
function deleteWork(key,name){presets[key]=worksFor(key).filter(w=>w!==name);videos=videos.map(v=>v.category===key&&v.work===name?{...v,work:''}:v);if(selectedCategory===key&&selectedWork===name)selectedWork=''}
function managedRow(value,max,saveAction,deleteAction){const row=node('div','manage-row'),input=node('input');input.value=value;input.maxLength=max;input.setAttribute('aria-label',value+' 이름');const update=node('button','secondary','변경'),remove=node('button','delete','삭제');update.onclick=()=>{try{saveAction(input.value);manageError('');persistManagement()}catch(e){manageError(e.message)}};remove.onclick=deleteAction;row.append(input,update,remove);return row}
function renderManager(){categoryOptions($('manageCategory'));$('categoryRows').replaceChildren(node('div','managed-fixed','미분류 · 기본 카테고리'));Object.entries(categories).filter(([k])=>k!=='unclassified').forEach(([k,name])=>$('categoryRows').append(managedRow(name,60,n=>renameCategory(k,n),()=>{if(confirm('이 카테고리를 삭제할까요? 해당 영상은 미분류로 옮겨지고 작품명과 메모는 유지됩니다.')){deleteCategory(k);persistManagement()}})));const c=$('manageCategory').value;$('workRows').replaceChildren(...worksFor(c).map(w=>managedRow(w,100,n=>renameWork(c,w,n),()=>{if(confirm('이 작품명을 삭제할까요? 해당 영상의 작품명만 비워집니다.')){deleteWork(c,w);persistManagement()}})));if(!worksFor(c).length)$('workRows').append(node('p','hint','등록된 작품명이 없습니다. 아래에서 추가하세요.'))}
$('manage').onclick=()=>{manageError('');renderManager();$('manager').showModal()};$('closeManager').onclick=()=>$('manager').close();$('manageCategory').onchange=()=>{manageError('');renderManager()};
$('newCategoryForm').onsubmit=e=>{e.preventDefault();const name=$('newCategory').value.trim();if(!name||name.length>60){manageError('카테고리 이름을 1~60자로 입력하세요.');return}if(Object.values(categories).includes(name)){manageError('이미 있는 카테고리 이름입니다.');return}if(Object.keys(categories).length>=100){manageError('카테고리는 최대 100개까지 등록할 수 있습니다.');return}const key=newCategoryId();categories[key]=name;presets[key]=[];$('newCategory').value='';manageError('');persistManagement();$('manageCategory').value=key;renderManager()};
$('newWorkForm').onsubmit=e=>{e.preventDefault();const c=$('manageCategory').value,w=$('newWork').value.trim();if(!w||w.length>100){manageError('작품명을 1~100자로 입력하세요.');return}if(worksFor(c).includes(w)){manageError('이미 있는 작품명입니다.');return}presets[c]=[...worksFor(c),w];$('newWork').value='';manageError('');persistManagement()};render();

window.Watchparty={getState:()=>JSON.parse(JSON.stringify(backup())),applyState:data=>{if(data?.version!==2||!catalogValid(data.categories,data.presets)||!Array.isArray(data.videos)||!data.videos.every(valid))throw Error('올바른 Watchparty 목록이 아닙니다.');applyCatalog(data.categories,data.presets);videos=data.videos.map(normalize);selectedCategory='all';selectedWork='';localStorage.setItem(KEY,JSON.stringify(backup()));render()},updateThumbnail:(id,fileId)=>{const v=videos.find(v=>v.id===id);if(v){v.thumbnailFileId=fileId;localStorage.setItem(KEY,JSON.stringify(backup()))}},render};
